// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_work_time/test/presentation/view_models/dashboard_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/material.dart' as _i8;
import 'package:flutter_work_time/domain/entities/work_entry_entity.dart'
    as _i2;
import 'package:flutter_work_time/domain/repositories/overtime_repository.dart'
    as _i3;
import 'package:flutter_work_time/domain/repositories/settings_repository.dart'
    as _i7;
import 'package:flutter_work_time/domain/usecases/get_today_work_entry.dart'
    as _i4;
import 'package:flutter_work_time/domain/usecases/overtime_usecases.dart'
    as _i6;
import 'package:flutter_work_time/domain/usecases/save_work_entry.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWorkEntryEntity_0 extends _i1.SmartFake
    implements _i2.WorkEntryEntity {
  _FakeWorkEntryEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOvertimeRepository_1 extends _i1.SmartFake
    implements _i3.OvertimeRepository {
  _FakeOvertimeRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTodayWorkEntry].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTodayWorkEntry extends _i1.Mock implements _i4.GetTodayWorkEntry {
  MockGetTodayWorkEntry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.WorkEntryEntity> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i5.Future<_i2.WorkEntryEntity>.value(_FakeWorkEntryEntity_0(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i2.WorkEntryEntity>);
}

/// A class which mocks [GetOvertime].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOvertime extends _i1.Mock implements _i6.GetOvertime {
  MockGetOvertime() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.OvertimeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeOvertimeRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.OvertimeRepository);

  @override
  Duration call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _FakeDuration_2(
          this,
          Invocation.method(
            #call,
            [],
          ),
        ),
      ) as Duration);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i7.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.ThemeMode getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i8.ThemeMode.system,
      ) as _i8.ThemeMode);

  @override
  _i5.Future<void> setThemeMode(_i8.ThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  double getTargetWeeklyHours() => (super.noSuchMethod(
        Invocation.method(
          #getTargetWeeklyHours,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i5.Future<void> setTargetWeeklyHours(double? hours) => (super.noSuchMethod(
        Invocation.method(
          #setTargetWeeklyHours,
          [hours],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  int getWorkdaysPerWeek() => (super.noSuchMethod(
        Invocation.method(
          #getWorkdaysPerWeek,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i5.Future<void> setWorkdaysPerWeek(int? days) => (super.noSuchMethod(
        Invocation.method(
          #setWorkdaysPerWeek,
          [days],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool hasAcceptedTermsOfService() => (super.noSuchMethod(
        Invocation.method(
          #hasAcceptedTermsOfService,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setAcceptedTermsOfService(bool? accepted) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAcceptedTermsOfService,
          [accepted],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool hasAcceptedPrivacyPolicy() => (super.noSuchMethod(
        Invocation.method(
          #hasAcceptedPrivacyPolicy,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setAcceptedPrivacyPolicy(bool? accepted) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAcceptedPrivacyPolicy,
          [accepted],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool getNotificationsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationsEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setNotificationsEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  String getNotificationTime() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationTime,
          [],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #getNotificationTime,
            [],
          ),
        ),
      ) as String);

  @override
  _i5.Future<void> setNotificationTime(String? time) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationTime,
          [time],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<int> getNotificationDays() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationDays,
          [],
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i5.Future<void> setNotificationDays(List<int>? days) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationDays,
          [days],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool getNotifyWorkStart() => (super.noSuchMethod(
        Invocation.method(
          #getNotifyWorkStart,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setNotifyWorkStart(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setNotifyWorkStart,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool getNotifyWorkEnd() => (super.noSuchMethod(
        Invocation.method(
          #getNotifyWorkEnd,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setNotifyWorkEnd(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setNotifyWorkEnd,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool getNotifyBreaks() => (super.noSuchMethod(
        Invocation.method(
          #getNotifyBreaks,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setNotifyBreaks(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setNotifyBreaks,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SaveWorkEntry].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWorkEntry extends _i1.Mock implements _i10.SaveWorkEntry {
  MockSaveWorkEntry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call(_i2.WorkEntryEntity? entry) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [OvertimeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOvertimeRepository extends _i1.Mock
    implements _i3.OvertimeRepository {
  MockOvertimeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration getOvertime() => (super.noSuchMethod(
        Invocation.method(
          #getOvertime,
          [],
        ),
        returnValue: _FakeDuration_2(
          this,
          Invocation.method(
            #getOvertime,
            [],
          ),
        ),
      ) as Duration);

  @override
  _i5.Future<void> saveOvertime(Duration? overtime) => (super.noSuchMethod(
        Invocation.method(
          #saveOvertime,
          [overtime],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveLastUpdateDate(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #saveLastUpdateDate,
          [date],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
