// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_work_time/test/presentation/screens/settings_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i3;
import 'package:flutter_work_time/domain/usecases/delete_account.dart' as _i6;
import 'package:flutter_work_time/domain/usecases/sign_out.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

import 'settings_page_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SettingsActions].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsActions extends _i1.Mock implements _i2.SettingsActions {
  MockSettingsActions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setTheme(_i3.ThemeMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTargetHours(double? hours) => (super.noSuchMethod(
        Invocation.method(
          #updateTargetHours,
          [hours],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateWorkdays(int? days) => (super.noSuchMethod(
        Invocation.method(
          #updateWorkdays,
          [days],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SignOut].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOut extends _i1.Mock implements _i5.SignOut {
  MockSignOut() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [DeleteAccount].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAccount extends _i1.Mock implements _i6.DeleteAccount {
  MockDeleteAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
