// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_work_time/test/presentation/view_models/reports_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i6;
import 'package:flutter_work_time/domain/entities/work_entry_entity.dart'
    as _i2;
import 'package:flutter_work_time/domain/repositories/settings_repository.dart'
    as _i5;
import 'package:flutter_work_time/domain/repositories/work_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWorkEntryEntity_0 extends _i1.SmartFake
    implements _i2.WorkEntryEntity {
  _FakeWorkEntryEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkRepository extends _i1.Mock implements _i3.WorkRepository {
  MockWorkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WorkEntryEntity> getWorkEntry(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkEntry,
          [date],
        ),
        returnValue:
            _i4.Future<_i2.WorkEntryEntity>.value(_FakeWorkEntryEntity_0(
          this,
          Invocation.method(
            #getWorkEntry,
            [date],
          ),
        )),
      ) as _i4.Future<_i2.WorkEntryEntity>);

  @override
  _i4.Future<void> saveWorkEntry(_i2.WorkEntryEntity? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWorkEntry,
          [entry],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.WorkEntryEntity>> getWorkEntriesForMonth(
    int? year,
    int? month,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkEntriesForMonth,
          [
            year,
            month,
          ],
        ),
        returnValue: _i4.Future<List<_i2.WorkEntryEntity>>.value(
            <_i2.WorkEntryEntity>[]),
      ) as _i4.Future<List<_i2.WorkEntryEntity>>);

  @override
  _i4.Future<void> deleteWorkEntry(String? entryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteWorkEntry,
          [entryId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i5.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ThemeMode getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i6.ThemeMode.system,
      ) as _i6.ThemeMode);

  @override
  _i4.Future<void> setThemeMode(_i6.ThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  double getTargetWeeklyHours() => (super.noSuchMethod(
        Invocation.method(
          #getTargetWeeklyHours,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Future<void> setTargetWeeklyHours(double? hours) => (super.noSuchMethod(
        Invocation.method(
          #setTargetWeeklyHours,
          [hours],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int getWorkdaysPerWeek() => (super.noSuchMethod(
        Invocation.method(
          #getWorkdaysPerWeek,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> setWorkdaysPerWeek(int? days) => (super.noSuchMethod(
        Invocation.method(
          #setWorkdaysPerWeek,
          [days],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool hasAcceptedTermsOfService() => (super.noSuchMethod(
        Invocation.method(
          #hasAcceptedTermsOfService,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setAcceptedTermsOfService(bool? accepted) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAcceptedTermsOfService,
          [accepted],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool hasAcceptedPrivacyPolicy() => (super.noSuchMethod(
        Invocation.method(
          #hasAcceptedPrivacyPolicy,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setAcceptedPrivacyPolicy(bool? accepted) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAcceptedPrivacyPolicy,
          [accepted],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getNotificationsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationsEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setNotificationsEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String getNotificationTime() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationTime,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getNotificationTime,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<void> setNotificationTime(String? time) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationTime,
          [time],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<int> getNotificationDays() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationDays,
          [],
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i4.Future<void> setNotificationDays(List<int>? days) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationDays,
          [days],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getNotifyWorkStart() => (super.noSuchMethod(
        Invocation.method(
          #getNotifyWorkStart,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setNotifyWorkStart(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setNotifyWorkStart,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getNotifyWorkEnd() => (super.noSuchMethod(
        Invocation.method(
          #getNotifyWorkEnd,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setNotifyWorkEnd(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setNotifyWorkEnd,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getNotifyBreaks() => (super.noSuchMethod(
        Invocation.method(
          #getNotifyBreaks,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setNotifyBreaks(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setNotifyBreaks,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
