// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_work_time/test/presentation/view_models/settings_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_work_time/domain/entities/app_theme_mode.dart' as _i3;
import 'package:flutter_work_time/domain/entities/bundesland.dart' as _i6;
import 'package:flutter_work_time/domain/repositories/overtime_repository.dart'
    as _i7;
import 'package:flutter_work_time/domain/repositories/settings_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i2.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AppThemeMode getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i3.AppThemeMode.system,
      ) as _i3.AppThemeMode);

  @override
  _i4.Future<void> setThemeMode(_i3.AppThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  double getTargetWeeklyHours() => (super.noSuchMethod(
        Invocation.method(
          #getTargetWeeklyHours,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Future<void> setTargetWeeklyHours(double? hours) => (super.noSuchMethod(
        Invocation.method(
          #setTargetWeeklyHours,
          [hours],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<int> getWorkdays() => (super.noSuchMethod(
        Invocation.method(
          #getWorkdays,
          [],
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i4.Future<void> setWorkdays(List<int>? days) => (super.noSuchMethod(
        Invocation.method(
          #setWorkdays,
          [days],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool hasAcceptedTermsOfService() => (super.noSuchMethod(
        Invocation.method(
          #hasAcceptedTermsOfService,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setAcceptedTermsOfService(bool? accepted) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAcceptedTermsOfService,
          [accepted],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool hasAcceptedPrivacyPolicy() => (super.noSuchMethod(
        Invocation.method(
          #hasAcceptedPrivacyPolicy,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setAcceptedPrivacyPolicy(bool? accepted) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAcceptedPrivacyPolicy,
          [accepted],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getNotificationsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationsEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setNotificationsEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String getNotificationTime() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationTime,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getNotificationTime,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<void> setNotificationTime(String? time) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationTime,
          [time],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<int> getNotificationDays() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationDays,
          [],
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i4.Future<void> setNotificationDays(List<int>? days) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationDays,
          [days],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getNotifyWorkStart() => (super.noSuchMethod(
        Invocation.method(
          #getNotifyWorkStart,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setNotifyWorkStart(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setNotifyWorkStart,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getNotifyWorkEnd() => (super.noSuchMethod(
        Invocation.method(
          #getNotifyWorkEnd,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setNotifyWorkEnd(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setNotifyWorkEnd,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getNotifyBreaks() => (super.noSuchMethod(
        Invocation.method(
          #getNotifyBreaks,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setNotifyBreaks(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setNotifyBreaks,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setBundesland(_i6.Bundesland? bundesland) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBundesland,
          [bundesland],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getWarnOnOvertimeThreshold() => (super.noSuchMethod(
        Invocation.method(
          #getWarnOnOvertimeThreshold,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setWarnOnOvertimeThreshold(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWarnOnOvertimeThreshold,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  double getOvertimeThresholdHours() => (super.noSuchMethod(
        Invocation.method(
          #getOvertimeThresholdHours,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Future<void> setOvertimeThresholdHours(double? hours) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOvertimeThresholdHours,
          [hours],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getWarnOnUndertimeThreshold() => (super.noSuchMethod(
        Invocation.method(
          #getWarnOnUndertimeThreshold,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setWarnOnUndertimeThreshold(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWarnOnUndertimeThreshold,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  double getUndertimeThresholdHours() => (super.noSuchMethod(
        Invocation.method(
          #getUndertimeThresholdHours,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Future<void> setUndertimeThresholdHours(double? hours) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUndertimeThresholdHours,
          [hours],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getUse24HourFormat() => (super.noSuchMethod(
        Invocation.method(
          #getUse24HourFormat,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setUse24HourFormat(bool? use24Hour) => (super.noSuchMethod(
        Invocation.method(
          #setUse24HourFormat,
          [use24Hour],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setTimezoneOverride(String? timezone) => (super.noSuchMethod(
        Invocation.method(
          #setTimezoneOverride,
          [timezone],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String getLocale() => (super.noSuchMethod(
        Invocation.method(
          #getLocale,
          [],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getLocale,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<void> setLocale(String? locale) => (super.noSuchMethod(
        Invocation.method(
          #setLocale,
          [locale],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int getVacationDaysPerYear() => (super.noSuchMethod(
        Invocation.method(
          #getVacationDaysPerYear,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> setVacationDaysPerYear(int? days) => (super.noSuchMethod(
        Invocation.method(
          #setVacationDaysPerYear,
          [days],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [OvertimeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOvertimeRepository extends _i1.Mock
    implements _i7.OvertimeRepository {
  MockOvertimeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration getOvertime() => (super.noSuchMethod(
        Invocation.method(
          #getOvertime,
          [],
        ),
        returnValue: _FakeDuration_0(
          this,
          Invocation.method(
            #getOvertime,
            [],
          ),
        ),
      ) as Duration);

  @override
  _i4.Future<void> saveOvertime(Duration? overtime) => (super.noSuchMethod(
        Invocation.method(
          #saveOvertime,
          [overtime],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveLastUpdateDate(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #saveLastUpdateDate,
          [date],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Duration> ensureOvertimeLoaded() => (super.noSuchMethod(
        Invocation.method(
          #ensureOvertimeLoaded,
          [],
        ),
        returnValue: _i4.Future<Duration>.value(_FakeDuration_0(
          this,
          Invocation.method(
            #ensureOvertimeLoaded,
            [],
          ),
        )),
      ) as _i4.Future<Duration>);

  @override
  _i4.Future<DateTime?> ensureLastUpdateLoaded() => (super.noSuchMethod(
        Invocation.method(
          #ensureLastUpdateLoaded,
          [],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);
}
