// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_work_time/test/presentation/view_models/weekly_reflection_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_work_time/domain/entities/weekly_reflection_entity.dart'
    as _i4;
import 'package:flutter_work_time/domain/repositories/weekly_reflection_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [WeeklyReflectionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeeklyReflectionRepository extends _i1.Mock
    implements _i2.WeeklyReflectionRepository {
  MockWeeklyReflectionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.WeeklyReflectionEntity?> getReflection(
    int? year,
    int? week,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReflection,
          [
            year,
            week,
          ],
        ),
        returnValue: _i3.Future<_i4.WeeklyReflectionEntity?>.value(),
      ) as _i3.Future<_i4.WeeklyReflectionEntity?>);

  @override
  _i3.Future<void> saveReflection(_i4.WeeklyReflectionEntity? reflection) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveReflection,
          [reflection],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
