// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_work_time/test/data/datasources/remote/api_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:flutter_work_time/data/datasources/remote/api_client.dart'
    as _i8;
import 'package:flutter_work_time/data/datasources/remote/firestore_datasource.dart'
    as _i2;
import 'package:flutter_work_time/data/models/work_entry_model.dart' as _i5;
import 'package:flutter_work_time/domain/entities/weekly_reflection_entity.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreDataSource extends _i1.Mock
    implements _i2.FirestoreDataSource {
  MockFirestoreDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i3.Stream<_i4.User?>.empty(),
      ) as _i3.Stream<_i4.User?>);

  @override
  _i3.Future<void> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> reauthenticate() => (super.noSuchMethod(
        Invocation.method(
          #reauthenticate,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i5.WorkEntryModel?> getWorkEntry(
    String? userId,
    DateTime? date, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkEntry,
          [
            userId,
            date,
          ],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<_i5.WorkEntryModel?>.value(),
      ) as _i3.Future<_i5.WorkEntryModel?>);

  @override
  _i3.Future<void> saveWorkEntry(
    String? userId,
    _i5.WorkEntryModel? model, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWorkEntry,
          [
            userId,
            model,
          ],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.WorkEntryModel>> getWorkEntriesForMonth(
    String? userId,
    int? year,
    int? month, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkEntriesForMonth,
          [
            userId,
            year,
            month,
          ],
          {#profileId: profileId},
        ),
        returnValue:
            _i3.Future<List<_i5.WorkEntryModel>>.value(<_i5.WorkEntryModel>[]),
      ) as _i3.Future<List<_i5.WorkEntryModel>>);

  @override
  _i3.Future<void> deleteWorkEntry(
    String? userId,
    String? entryId, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWorkEntry,
          [
            userId,
            entryId,
          ],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Duration> getOvertime(
    String? userId, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOvertime,
          [userId],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<Duration>.value(_FakeDuration_0(
          this,
          Invocation.method(
            #getOvertime,
            [userId],
            {#profileId: profileId},
          ),
        )),
      ) as _i3.Future<Duration>);

  @override
  _i3.Future<void> saveOvertime(
    String? userId,
    Duration? overtime, {
    String? profileId,
    bool? keepLastUpdated = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOvertime,
          [
            userId,
            overtime,
          ],
          {
            #profileId: profileId,
            #keepLastUpdated: keepLastUpdated,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<DateTime?> getLastOvertimeUpdate(
    String? userId, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastOvertimeUpdate,
          [userId],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<DateTime?>.value(),
      ) as _i3.Future<DateTime?>);

  @override
  _i3.Future<void> saveLastOvertimeUpdate(
    String? userId,
    DateTime? date, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLastOvertimeUpdate,
          [
            userId,
            date,
          ],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setUserProfile(
    String? userId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserProfile,
          [
            userId,
            data,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getSettings(
    String? userId, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [userId],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> saveSettings(
    String? userId,
    Map<String, dynamic>? settings, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [
            userId,
            settings,
          ],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i6.WeeklyReflectionEntity?> getWeeklyReflection(
    String? userId,
    int? year,
    int? week,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeeklyReflection,
          [
            userId,
            year,
            week,
          ],
        ),
        returnValue: _i3.Future<_i6.WeeklyReflectionEntity?>.value(),
      ) as _i3.Future<_i6.WeeklyReflectionEntity?>);

  @override
  _i3.Future<void> saveWeeklyReflection(
    String? userId,
    _i6.WeeklyReflectionEntity? reflection,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWeeklyReflection,
          [
            userId,
            reflection,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getWorkProfiles(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkProfiles,
          [userId],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<String> addWorkProfile(
    String? userId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWorkProfile,
          [
            userId,
            name,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #addWorkProfile,
            [
              userId,
              name,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> deleteWorkProfile(
    String? userId,
    String? profileId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWorkProfile,
          [
            userId,
            profileId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i8.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.WorkEntryModel>> getWorkEntriesForMonth(
    int? year,
    int? month, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkEntriesForMonth,
          [
            year,
            month,
          ],
          {#profileId: profileId},
        ),
        returnValue:
            _i3.Future<List<_i5.WorkEntryModel>>.value(<_i5.WorkEntryModel>[]),
      ) as _i3.Future<List<_i5.WorkEntryModel>>);

  @override
  _i3.Future<_i5.WorkEntryModel?> getWorkEntry(
    int? year,
    int? month,
    int? day, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkEntry,
          [
            year,
            month,
            day,
          ],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<_i5.WorkEntryModel?>.value(),
      ) as _i3.Future<_i5.WorkEntryModel?>);

  @override
  _i3.Future<void> saveWorkEntry(
    _i5.WorkEntryModel? model, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWorkEntry,
          [model],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteWorkEntry(
    int? year,
    int? month,
    int? day, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWorkEntry,
          [
            year,
            month,
            day,
          ],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<({DateTime? lastUpdated, int minutes})> getOvertime(
          {String? profileId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOvertime,
          [],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<({DateTime? lastUpdated, int minutes})>.value(
            (lastUpdated: null, minutes: 0)),
      ) as _i3.Future<({DateTime? lastUpdated, int minutes})>);

  @override
  _i3.Future<void> saveOvertime(
    int? minutes, {
    String? profileId,
    bool? keepLastUpdated = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOvertime,
          [minutes],
          {
            #profileId: profileId,
            #keepLastUpdated: keepLastUpdated,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getSettings({String? profileId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> putSettings(
    Map<String, dynamic>? settings, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putSettings,
          [settings],
          {#profileId: profileId},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getDailyReport(
    int? year,
    int? month,
    int? day, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailyReport,
          [
            year,
            month,
            day,
          ],
          {#profileId: profileId},
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getWeeklyReport(
    int? year,
    int? month,
    int? day, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeeklyReport,
          [
            year,
            month,
            day,
          ],
          {#profileId: profileId},
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getMonthlyReport(
    int? year,
    int? month, {
    String? profileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyReport,
          [
            year,
            month,
          ],
          {#profileId: profileId},
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}
