// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_work_time/test/data/repositories/firebase_overtime_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:flutter_work_time/data/datasources/remote/firestore_datasource.dart'
    as _i2;
import 'package:flutter_work_time/data/models/work_entry_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreDataSource extends _i1.Mock
    implements _i2.FirestoreDataSource {
  MockFirestoreDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i3.Stream<_i4.User?>.empty(),
      ) as _i3.Stream<_i4.User?>);

  @override
  _i3.Future<void> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i5.WorkEntryModel?> getWorkEntry(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkEntry,
          [
            userId,
            date,
          ],
        ),
        returnValue: _i3.Future<_i5.WorkEntryModel?>.value(),
      ) as _i3.Future<_i5.WorkEntryModel?>);

  @override
  _i3.Future<void> saveWorkEntry(
    String? userId,
    _i5.WorkEntryModel? model,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWorkEntry,
          [
            userId,
            model,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.WorkEntryModel>> getWorkEntriesForMonth(
    String? userId,
    int? year,
    int? month,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkEntriesForMonth,
          [
            userId,
            year,
            month,
          ],
        ),
        returnValue:
            _i3.Future<List<_i5.WorkEntryModel>>.value(<_i5.WorkEntryModel>[]),
      ) as _i3.Future<List<_i5.WorkEntryModel>>);

  @override
  _i3.Future<void> deleteWorkEntry(
    String? userId,
    String? entryId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWorkEntry,
          [
            userId,
            entryId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Duration> getOvertime(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getOvertime,
          [userId],
        ),
        returnValue: _i3.Future<Duration>.value(_FakeDuration_0(
          this,
          Invocation.method(
            #getOvertime,
            [userId],
          ),
        )),
      ) as _i3.Future<Duration>);

  @override
  _i3.Future<void> saveOvertime(
    String? userId,
    Duration? overtime,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOvertime,
          [
            userId,
            overtime,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<DateTime?> getLastOvertimeUpdate(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastOvertimeUpdate,
          [userId],
        ),
        returnValue: _i3.Future<DateTime?>.value(),
      ) as _i3.Future<DateTime?>);

  @override
  _i3.Future<void> saveLastOvertimeUpdate(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLastOvertimeUpdate,
          [
            userId,
            date,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
