// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_work_time/test/domain/usecases/overtime_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_work_time/domain/repositories/overtime_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OvertimeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOvertimeRepository extends _i1.Mock
    implements _i2.OvertimeRepository {
  MockOvertimeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration getOvertime() => (super.noSuchMethod(
        Invocation.method(
          #getOvertime,
          [],
        ),
        returnValue: _FakeDuration_0(
          this,
          Invocation.method(
            #getOvertime,
            [],
          ),
        ),
      ) as Duration);

  @override
  _i3.Future<void> saveOvertime(Duration? overtime) => (super.noSuchMethod(
        Invocation.method(
          #saveOvertime,
          [overtime],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveLastUpdateDate(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #saveLastUpdateDate,
          [date],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
