services:
  work-time-manager-web:
    image: riksorax/work-time-manager-web:latest
    container_name: work-time-manager-web
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      # Traefik aktivieren
      - "traefik.enable=true"
      # HTTPS-Router
      - "traefik.http.routers.work-time-manager.rule=Host(`work-time-manager.app`)"
      - "traefik.http.routers.work-time-manager.entrypoints=websecure"
      - "traefik.http.routers.work-time-manager.tls.certresolver=letsencrypt"
      # Port im Container (nginx läuft auf 80)
      - "traefik.http.services.work-time-manager.loadbalancer.server.port=8080"
      # HTTP → HTTPS Redirect
      - "traefik.http.routers.work-time-manager-web.rule=Host(`work-time-manager.app`)"
      - "traefik.http.routers.work-time-manager-web.entrypoints=web"
      - "traefik.http.routers.work-time-manager-web.middlewares=wtm-https-redirect"
      - "traefik.http.middlewares.wtm-https-redirect.redirectscheme.scheme=https"

networks:
  traefik-proxy:
    external: true
