// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlBWIrPPlT8NaH2sWzrl3jsp_tVVM9KJM',
    appId: '1:915742606352:web:4d45e8efd80b917421f695',
    messagingSenderId: '915742606352',
    projectId: 'worktime-56c7a',
    authDomain: 'worktime-56c7a.firebaseapp.com',
    storageBucket: 'worktime-56c7a.firebasestorage.app',
    measurementId: 'G-9H2D22VWDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGqvPYrz8zpgWwuVTizEE7IT068Ui7les',
    appId: '1:915742606352:android:53d65a429a75b3f121f695',
    messagingSenderId: '915742606352',
    projectId: 'worktime-56c7a',
    storageBucket: 'worktime-56c7a.firebasestorage.app',
  );

}