import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_work_time/data/models/break_model.dart';
import 'package:flutter_work_time/domain/entities/break_entity.dart';

void main() {
  group('BreakModel', () {
    final start = DateTime(2023, 10, 26, 12, 0);
    final end = DateTime(2023, 10, 26, 12, 30);

    test('should create a valid BreakModel from Entity', () {
      final entity = BreakEntity(
        id: '123',
        name: 'Lunch',
        start: start,
        end: end,
      );

      final model = BreakModel.fromEntity(entity);

      expect(model.name, 'Lunch');
      expect(model.start, start);
      expect(model.end, end);
      // id is auto-generated by the constructor in current implementation
      expect(model.id, isNotEmpty);
    });

    test('should serialize to Map correctly', () {
      final model = BreakModel(
        name: 'Coffee',
        start: start,
        end: end,
      );

      final map = model.toMap();

      expect(map['name'], 'Coffee');
      expect(map['start'], isA<Timestamp>());
      expect((map['start'] as Timestamp).toDate(), start);
      expect((map['end'] as Timestamp).toDate(), end);
    });

    test('should deserialize from Map correctly', () {
      final map = {
        'name': 'Meeting',
        'start': Timestamp.fromDate(start),
        'end': Timestamp.fromDate(end),
      };

      final model = BreakModel.fromMap(map);

      expect(model.name, 'Meeting');
      expect(model.start, start);
      expect(model.end, end);
    });

    test('should handle optional end date in toMap/fromMap', () {
       final model = BreakModel(
        name: 'Start Only',
        start: start,
        end: null,
      );

      final map = model.toMap();
      expect(map['end'], isNull);

      final modelFromMap = BreakModel.fromMap(map);
      expect(modelFromMap.end, isNull);
    });
  });
}
